-- Executa este ficheiro no SQL Editor do Supabase antes de iniciar a aplicacao.

CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  telefone VARCHAR(50),
  email VARCHAR(255),
  nif VARCHAR(20) UNIQUE,
  morada VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS estados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO estados (nome) VALUES
  ('Pendente'), ('Em execucao'), ('Concluida'), ('Suspensa')
ON CONFLICT (nome) DO NOTHING;

CREATE TABLE IF NOT EXISTS funcionarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  username VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'funcionario',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT funcionarios_role_check CHECK (role IN ('admin', 'funcionario'))
);

CREATE TABLE IF NOT EXISTS obras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_obra VARCHAR(255) NOT NULL,
  descricao TEXT,
  id_cliente BIGINT NOT NULL REFERENCES clientes(id),
  id_estado BIGINT NOT NULL REFERENCES estados(id),
  data_fim_prevista DATE,
  prioridade VARCHAR(20) NOT NULL DEFAULT 'medium',
  observacoes TEXT,
  process_steps_configured BOOLEAN NOT NULL DEFAULT FALSE,
  public_access_token_hash VARCHAR(64),
  public_access_created_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT obras_prioridade_check CHECK (prioridade IN ('low', 'medium', 'high'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_obras_public_access_token_hash
  ON obras(public_access_token_hash)
  WHERE public_access_token_hash IS NOT NULL;

CREATE TABLE IF NOT EXISTS materiais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_obra BIGINT NOT NULL REFERENCES obras(id) ON DELETE CASCADE,
  nome_material VARCHAR(120) NOT NULL,
  pdf_path VARCHAR(255),
  encomendado BOOLEAN NOT NULL DEFAULT FALSE,
  chegou BOOLEAN NOT NULL DEFAULT FALSE,
  data_encomenda DATE,
  data_chegada DATE,
  nota_encomenda TEXT,
  invoice_photo_path VARCHAR(255),
  note_encomenda_pdf_path VARCHAR(255),
  ordered_by_user_id BIGINT,
  ordered_by_username VARCHAR(120),
  ordered_at TIMESTAMPTZ,
  arrived_by_user_id BIGINT,
  arrived_by_username VARCHAR(120),
  arrived_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (id_obra, nome_material)
);

CREATE INDEX IF NOT EXISTS idx_materiais_obra ON materiais(id_obra);

CREATE TABLE IF NOT EXISTS obra_etapas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_obra BIGINT NOT NULL REFERENCES obras(id) ON DELETE CASCADE,
  nome_etapa VARCHAR(120) NOT NULL,
  pdf_path VARCHAR(255),
  concluida BOOLEAN NOT NULL DEFAULT FALSE,
  order_index INTEGER NOT NULL DEFAULT 0,
  checked_by_user_id BIGINT,
  checked_by_username VARCHAR(120),
  checked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (id_obra, nome_etapa)
);

CREATE INDEX IF NOT EXISTS idx_obra_etapas_obra ON obra_etapas(id_obra);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  username VARCHAR(120),
  user_role VARCHAR(50),
  action_type VARCHAR(120) NOT NULL DEFAULT '',
  entity_type VARCHAR(120) NOT NULL DEFAULT '',
  entity_id BIGINT,
  work_id BIGINT,
  details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_work_id ON audit_logs(work_id);
